---
title: "Cant variable climate AD"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths, include=FALSE}

path_cmorized <-
  "/nfs/kryo/work/updata/reccap2/Models/3D_ALL/"

path_preprocessing <-
  paste0(path_root, "/model/preprocessing/")

```

```{r load_libraries_specific, include=FALSE}
library(tidync)
library(stars)
library(gsw)
library(lubridate)
```

```{r select_basin_mask}

# use only three basin to assign general basin mask
# ie this is not specific to the MLR fitting
basinmask <- basinmask %>%
  filter(MLR_basins == "2") %>%
  select(lat, lon, basin_AIP)

```


```{r create_list_of_models}

models <- list.files(path_cmorized)

models <-
  models[!str_detect(models, pattern = "\\.t|\\.z")]

models <-
  models[str_detect(
    models,
    pattern = c(
      "CESM|CNRM|EC-Earth3|FESOM_REcoM_LR|MOM6-Princeton|MRI-ESM2-0|NorESM-OC1.2|ORCA025-GEOMAR|ORCA1-LIM3-PISCES|planktom12"
    )
  )]

# depth levels not available
models <-
  models[!str_detect(models, pattern = "CNRM")]

# files chunked into decades
models <-
  models[!str_detect(models, pattern = "ORCA025-GEOMAR")]

# no run D
models <-
  models[!str_detect(models, pattern = "MOM6-Princeton")]

```

# Calculate annual Cant field

```{r read_cmorized_Runs_A_D}

# for loop across variables
# 3d variables
variables <-
  c("so", "thetao", "dissic", "talk", "po4", "no3")


# models <- models[7]

for (i_model in models) {
  # i_model <- models[1]
  print(i_model)
  
  for (i_model_ID in c("A", "D")) {
    # i_model_ID <- c("A", "D")[2]
    
    print(i_model_ID)
    
    variables_available <-
      list.files(
        path = paste0(path_cmorized, i_model),
        pattern = paste0("_", i_model_ID, "_")
      )
    
    variables_available <-
      str_split(variables_available,
                pattern = "_",
                simplify = TRUE)[, 1]
    variables_available <-
      variables_available[variables_available %in% variables]
    variables_available <- unique(variables_available)
    print(variables_available)
    
    for (i_variable in variables_available) {
      #  i_variable <- variables_available[2]
      
      # read list of all files
      file <-
        list.files(
          path = paste0(path_cmorized, i_model),
          pattern = paste0(i_variable, "_")
        )
      
      if (i_model == "MRI-ESM2-0_3D_ALL_v20210830" &
          i_model_ID == "D" &
          i_variable %in% c("so", "thetao")) {
        file <-
          file[str_detect(file, pattern = paste0("_", "A", "_"))]
      } else {
        file <-
          file[str_detect(file, pattern = paste0("_", i_model_ID, "_"))]
      }
      
      print(file)
      
      # read in data
      if (i_model == "NorESM-OC1.2_3D_ALL_v20211125") {
        variable_data <-
          tidync::tidync(paste(paste0(path_cmorized, i_model),
                               file,
                               sep = "/")) %>%
          tidync::hyper_tibble() %>%
          mutate(time = as.Date(time, origin = "1980-01-01"))
      } else if (i_model %in% c("EC-Earth3_3D_ALL_v20220323",
                                "CNRM-ESM2-1_3D_ALL_v20211208")) {
        variable_data <-
          read_ncdf(paste(paste0(path_cmorized, i_model),
                          file,
                          sep = "/"),
                    make_units = FALSE,
                    make_time = FALSE)
      } else {
        variable_data <-
          read_ncdf(paste(paste0(path_cmorized, i_model),
                          file,
                          sep = "/"),
                    make_units = FALSE)
      }
      
      # convert to tibble
      variable_data_tibble <- variable_data %>%
        as_tibble()
      
      # remove open link to nc file
      rm(variable_data)
      
      # remove na values
      variable_data_tibble <-
        variable_data_tibble %>%
        filter(!is.na(!!sym(i_variable)))
      
      # sort(unique(variable_data_tibble$lev))
      # sort(unique(variable_data_tibble$lon))
      
      if (i_model == "CESM-ETHZ_3D_ALL_v20211122") {
        variable_data_tibble <- variable_data_tibble %>%
          rename(time = time_ann) %>%
          mutate(depth = as.numeric(depth))
      }
      
      if (i_model == "CNRM-ESM2-1_3D_ALL_v20211208") {
        variable_data_tibble <- variable_data_tibble %>%
          rename(depth = lev) %>%
          group_by(time) %>%
          mutate(year = as.character(1979 + cur_group_id())) %>%
          ungroup()
        
        variable_data_tibble <- variable_data_tibble %>%
          mutate(time = as.Date(year, format = "%Y")) %>%
          select(-year)
      }
      
      if (i_model == "EC-Earth3_3D_ALL_v20220323") {
        variable_data_tibble <- variable_data_tibble %>%
          mutate(time = as.Date(time, origin = "1850-06-01"))
      }
      
      if (i_model == "FESOM_REcoM_LR_3D_all_v20211119") {
        variable_data_tibble <- variable_data_tibble %>%
          rename(
            lat = Lat,
            lon = Lon,
            depth = Depth,
            time = Time
          ) %>%
          mutate(time = as.Date(time, origin = '1980-01-01'),
                 depth = as.numeric(depth))
      }
      
      if (i_model == "MOM6-Princeton_3D_ALL_v20220125") {
        variable_data_tibble <- variable_data_tibble %>%
          rename(depth = z_l)
      }
      
      if (i_model == "MRI-ESM2-0_3D_ALL_v20210830") {
        variable_data_tibble <- variable_data_tibble %>%
          rename(depth = lev)
      }
      
      if (i_model == "planktom12_3d_all_v20220404") {
        variable_data_tibble <- variable_data_tibble %>%
          rename(
            lon = LONGITUDE,
            lat = LATITUDE,
            depth = DEPTH,
            time = TIME
          ) %>%
          mutate(depth = as.numeric(depth))
      }
      
      if (i_model == "planktom12_3d_all_v20220404" &
          i_variable == "po4") {
        variable_data_tibble <-
          variable_data_tibble %>%
          mutate(po4 = po4 / 100)
      }
      
      variable_data_tibble <- variable_data_tibble %>%
        mutate(time = year(time))
      
      if (exists("annual")) {
        annual <- left_join(annual, variable_data_tibble)
      }
      
      if (!exists("annual")) {
        annual <- variable_data_tibble
      }
      
      rm(variable_data_tibble)
      
    }
    
    if (i_model == "FESOM_REcoM_LR_3D_all_v20211119") {
      annual <- annual %>%
        mutate(po4 = no3 / 16)
    }
    
    if (i_model == "planktom12_3d_all_v20220404") {
      annual <- annual %>%
        mutate(no3 = po4 * 16)
    }
    
    if (i_model == "MRI-ESM2-0_3D_ALL_v20210830" &
        i_model_ID == "D") {
      annual <- right_join(annual,
                           AD_annual %>%
                             select(-dissic))
    }
    
    annual <- annual %>%
      mutate(model_ID = i_model_ID)
    
    if (exists("AD_annual")) {
      AD_annual <- bind_rows(AD_annual, annual)
    }
    
    if (!exists("AD_annual")) {
      AD_annual <- annual
    }
    
    rm(annual)
    
  }
  
  # harmonize column names and coordinates
  AD_annual <- AD_annual %>%
    select(
      year = time,
      lon,
      lat,
      depth,
      sal = so,
      theta = thetao,
      dissic,
      talk,
      phosphate = po4,
      nitrate = no3,
      model_ID
    ) %>%
    mutate(lon = if_else(lon < 20, lon + 360, lon))
  
  # calculate model temperature
  AD_annual <- AD_annual %>%
    mutate(temp = gsw_pt_from_t(
      SA = sal,
      t = theta,
      p = 10.1325,
      p_ref = depth
    ))
  
  # unit transfer from mol/m3 to µmol/kg
  AD_annual <- AD_annual %>%
    mutate(
      rho = gsw_pot_rho_t_exact(
        SA = sal,
        t = temp,
        p = depth,
        p_ref = 10.1325
      ),
      dissic = dissic * (1e+6 / rho),
      talk = talk * (1e+6 / rho),
      phosphate = phosphate * (1e+6 / rho),
      nitrate = nitrate * (1e+6 / rho)
    )
  
  AD_annual <- AD_annual %>%
    select(-c(sal, temp, theta, rho))
  
  
  # sort(unique(AD_annual$depth))
  # sort(unique(AD_annual$lon))
  
  AD_annual <- AD_annual %>%
    mutate(depth = round(depth))
  
  ## Apply basin mask
  AD_annual <- inner_join(AD_annual, basinmask)
  
  # calculate cstar field
  AD_annual_cstar <- AD_annual

  params_local <- lst(rCP = 117,
                      rNP = 16)
  
  
  AD_annual_cstar <- AD_annual_cstar %>%
    mutate(
      cstar_no3 = b_cstar_nitrate(
        tco2 = dissic,
        nitrate = nitrate,
        talk = talk
      ),
      cstar_po4 = b_cstar_phosphate(
        tco2 = dissic,
        phosphate = phosphate,
        talk = talk
      )
    )
  
  rm(params_local)
  
  # Calculate Cant fields
  
  AD_annual <- AD_annual %>%
    select(year, lon, lat, depth, dissic, model_ID, basin_AIP)
  
  AD_annual <- AD_annual %>% pivot_wider(names_from = model_ID,
                                         values_from = dissic)
  
  
  AD_annual_dissic <- AD_annual
  
  AD_annual <- AD_annual %>%
    mutate(tcant = A - D) %>%
    select(-c(A, D))
  
  
  # Remove 3D_all from model name
  i_model <- str_remove(i_model, "3D_ALL_|3D_all_|3d_all_")
  
  # write annual Cant files
  for (i_year in unique(AD_annual$year)) {
    # i_year = unique(AD_annual$year)[1]
    AD_annual %>%
      filter(year == i_year) %>%
      write_csv(
        paste0(
          path_preprocessing,
          "Cant_AD_annual_all_models/",
          i_year,
          "_",
          i_model,
          ".csv"
        )
      )

    AD_annual_dissic %>%
      filter(year == i_year) %>%
      write_csv(
        paste0(
          path_preprocessing,
          "Cant_AD_annual_all_models/dissic/",
          i_year,
          "_",
          i_model,
          ".csv"
        )
      )
    
    AD_annual_cstar %>%
      filter(year == i_year,
             model_ID == "A") %>%
      write_csv(
        paste0(
          path_preprocessing,
          "Cstar_A_annual_all_models/",
          i_year,
          "_",
          i_model,
          ".csv"
        )
      )
    
    AD_annual_cstar %>%
      filter(year == i_year,
             model_ID == "D") %>%
      write_csv(
        paste0(
          path_preprocessing,
          "Cstar_D_annual_all_models/",
          i_year,
          "_",
          i_model,
          ".csv"
        )
      )
    
  }
  
  rm(AD_annual)
  
}


```

# Calculate change in Cant 1994 - 2004 - 2014

```{r read_tcant_fields}


for (i_model in models) {
  # i_model <- models[1]
  print(i_model)
  
  for (i_year in c("1994", "2004", "2014")) {
    # i_year = "1994"
    
    cant_year <-
      read_csv(paste0(path_preprocessing,
                      "Cant_AD_annual_all_models/",
                      i_year,
                      "_",
                      str_remove(i_model, "3D_ALL_|3D_all_|3d_all_"),
                      ".csv"))
    
    cant_year <- cant_year %>% 
      mutate(model = i_model)
    
    if (exists("tcant")) {
      tcant <- bind_rows(tcant, cant_year)
    }
    
    if (!exists("tcant")) {
      tcant <- cant_year
    }
    
  }
  
}

```



```{r calculate_dcant}

tcant <- tcant %>%
  # head(10) %>%
  arrange(year) %>%
  group_by(model, lon, lat, depth, basin_AIP) %>%
  mutate(dcant = tcant - lag(tcant),
         eras = paste(year, "-" , lag(year))) %>%
  ungroup()

```


# Zonal mean sections

```{r calc_zonal_mean_gruber}

tcant <- tcant %>% 
  rename(data_source = model)

tcant_zonal <- tcant %>%
  select(-year) %>% 
  filter(!is.na(dcant)) %>% 
  group_by(data_source, eras) %>%
  nest() %>%
  mutate(zonal = map(.x = data, ~m_zonal_mean_sd(.x))) %>%
  select(-data) %>%
  unnest(zonal)

```

## delta Cant

```{r zonal_mean_section_dcant, fig.asp=2}

tcant_zonal %>%
  filter(depth <= params_global$inventory_depth_standard) %>%
  group_by(basin_AIP) %>%
  group_split() %>%
  head(1) %>%
  map(
    ~ p_section_zonal_continous_depth(
      df = .x,
      var = "dcant_mean",
      plot_slabs = "n",
      subtitle_text = .x$basin_AIP
    ) +
      facet_grid(data_source ~ eras)
  )

```

## total Cant

```{r zonal_mean_section_tcant, fig.asp=2}

tcant_zonal %>%
  filter(depth <= params_global$inventory_depth_standard) %>%
  group_by(basin_AIP) %>%
  group_split() %>%
  # head(1) %>%
  map(
    ~ p_section_zonal_continous_depth(
      df = .x,
      var = "tcant_mean",
      plot_slabs = "n",
      subtitle_text = .x$basin_AIP,
      breaks = c(-Inf,seq(0,80,10), Inf)
    ) +
      facet_grid(data_source ~ eras)
  )

```


# Column inventory 

## delta Cant

```{r dcant_column_inventory, fig.asp=2}

dcant_inv <- tcant %>%
  select(-year) %>%
  filter(!is.na(dcant)) %>%
  mutate(dcant_pos = 0) %>%
  group_by(data_source, eras) %>%
  nest() %>%
  mutate(inv = map(.x = data, ~ m_dcant_inv(.x))) %>%
  select(-data) %>%
  unnest(inv)

dcant_inv %>%
  filter(inv_depth == params_global$inventory_depth_standard) %>%
  p_map_cant_inv(var = "dcant",
                 subtitle_text = "for predefined integration depths") +
  facet_grid(data_source ~ eras)

```

## Cant total

```{r calc_total_inventory_1994, eval=FALSE}

# this is just a work around, because the function is designed to calculate cant inventories, but not cant_total inventories

tcant_total_inv <- m_cant_inv(
  tcant %>% 
    select(-cant_pos) %>% 
    rename(cant_pos = cant_1994))

```

```{r cant_inventory_1994, eval=FALSE}

p_map_cant_inv(tcant_total_inv %>% filter(inv_depth == 3000),
               breaks = seq(0,100,10),
               subtitle_text = "Cant total in 1994")

```

