---
title: "Atmospheric pCO2"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths, include=FALSE}

path_cmorized    <-
  "/nfs/kryo/work/updata/reccap2/Models/Ancillary_data/"
path_preprocessing  <-
  paste0(path_root, "/model/preprocessing/co2_atm/")

```

```{r load_libraries_specific, include=FALSE}
library(lubridate)
library(tidync)
library(stars)
```

# Read data

```{r create_list_of_models}

models <- list.files(path_cmorized)

models <-
  models[!str_detect(models, pattern = "\\.t|\\.z|.p")]

models <-
  models[str_detect(
    models,
    pattern = c(
      "CESM|CNRM|EC-Earth3|FESOM_REcoM_LR|MOM6-Princeton|MRI-ESM2-1|NorESM-OC1.2|ORCA025-GEOMAR|ORCA1-LIM3-PISCES|planktom12"
    )
  )]

# no Atm_CO2 data provided
models <-
  models[!str_detect(models, pattern = "NorESM-OC1.2")]

# no Atm_CO2 data provided
models <-
  models[!str_detect(models, pattern = "ORCA1-LIM3-PISCES")]


```



```{r subset_cmorized_variable_forcing_data}

# models <- models[1]

for (i_model in models) {
  # i_model <- models[7]
  print(i_model)
  
  # read list of all files
  file <-
    list.files(path = paste0(path_cmorized, i_model),
               pattern = "CO2")[1]
  
  print(file)
  
  # read in data
  if (i_model %in% c(
    "CESM-ETHZ_Ancillary_data_v20211122",
    "MOM6-Princeton_Ancillary_data_v20220125",
    "ORCA025-GEOMAR_Ancillary_data_v20210804"
  )) {
    variable_data <-
      read_ncdf(paste(paste0(path_cmorized, i_model),
                      file,
                      sep = "/"),
                var = "Atm_CO2",
                make_units = FALSE)
  } else if (i_model == "CNRM-ESM2-1_Ancillary_data_v20211208") {
    variable_data <-
      read_delim(paste(paste0(path_cmorized, i_model),
                       file,
                       sep = "/"),
                 delim = " ") %>%
      rename(year = Year,
             Atm_CO2 = atmCO2)
    
  } else if (i_model == "EC-Earth3_Ancillary_data_v20220323") {
    variable_data <-
      read_table(paste(paste0(path_cmorized, i_model),
                       file,
                       sep = "/"),
                 col_names = FALSE) %>%
      rename(year = X1,
             Atm_CO2 = X2)
  } else if (i_model == "MRI-ESM2-1_Ancillary_data_v20220502") {
    variable_data <-
      tidync(paste(paste0(path_cmorized, i_model),
                   file,
                   sep = "/")) %>%
      activate("D0") %>%
      hyper_tibble() %>%
      mutate(time = as.Date(time, origin = "1980-01-01"))
  } else if (i_model == "planktom12_ancillary_data_v20220404") {
    variable_data <-
      read_table(paste(paste0(path_cmorized, i_model),
                       file,
                       sep = "/"),
                 col_names = FALSE) %>%
      select(year = X1,
             Atm_CO2 = X2)
  } else {
    variable_data <-
      read_ncdf(paste(paste0(path_cmorized, i_model),
                      file,
                      sep = "/"),
                make_units = FALSE)
  }
  
  # convert to tibble
  variable_data_tibble <- variable_data %>%
    as_tibble()
  
  # remove open link to nc file
  rm(variable_data)
  
  if (i_model == "CESM-ETHZ_Ancillary_data_v20211122") {
    variable_data_tibble <- variable_data_tibble %>%
      rename(time = time_ann)
  }
  
  if (i_model == "FESOM_REcoM_LR_Ancillary_data_v20211119") {
    variable_data_tibble <-
      variable_data_tibble %>%
      pivot_longer(
        cols = -NumberOfMonths,
        names_to = "year",
        values_to = "Atm_CO2",
        names_prefix = "AtmCO2_"
      ) %>%
      mutate(year = as.numeric(year))
  }
  
  # mutate variables
  if (!(
    i_model %in% c(
      "CNRM-ESM2-1_Ancillary_data_v20211208",
      "EC-Earth3_Ancillary_data_v20220323",
      "FESOM_REcoM_LR_Ancillary_data_v20211119",
      "planktom12_ancillary_data_v20220404"
    )
  )) {
    variable_data_tibble <- variable_data_tibble %>%
      mutate(year = year(time)) %>%
      select(-time)
  }
  
  variable_data_tibble <- variable_data_tibble %>%
    mutate(model = i_model)
  
  
  if (exists("atm_co2")) {
    atm_co2 <- bind_rows(atm_co2, variable_data_tibble)
  }
  
  if (!exists("atm_co2")) {
    atm_co2 <- variable_data_tibble
  }
  
}

atm_co2 <- atm_co2 %>%
  mutate(year = round(year)) %>%
  filter(year > 1979, year < 2019) %>%
  group_by(model, year) %>%
  summarise(Atm_CO2 = mean(Atm_CO2)) %>%
  ungroup()

atm_co2 <- atm_co2 %>%
  mutate(
    model = str_remove(model, "Ancillary_data_"),
    model = str_remove(model, "ancillary_data_")
  )


```


# Time series

```{r co2_atm_time_series, fig.asp=1}

atm_co2 %>% 
  ggplot(aes(year, Atm_CO2, col = model)) +
  geom_path() +
  geom_point() +
  scale_color_brewer(palette = "Dark2") +
  theme(legend.position = "bottom",
        legend.direction = "vertical")

```

# Write files

```{r write_co2_atm_clean_files}

atm_co2 %>%
  group_by(model) %>%
  group_walk( ~ write_csv(.x, paste0(
    path_preprocessing,
    .y$model,
    "_co2_atm.csv"
  )))

```
