---
title: "Parameterization"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r library, message=FALSE, warning=FALSE}
library(tidyverse)
```

```{r define_paths}
path_utilities  <- "/nfs/kryo/work/jenmueller/emlr_cant/utilities/"
```


# Definition

Following global parameterizations were chosen to run all analysis and display results:

```{r define_global_params_global, class.source = 'fold-show'}

depth_levels = c(0, 150, 500, 2000)

depth_levels_33 <- c(
  0,
  10,
  20,
  30,
  50,
  75,
  100,
  125,
  150,
  200,
  250,
  300,
  400,
  500,
  600,
  700,
  800,
  900,
  1000,
  1100,
  1200,
  1300,
  1400,
  1500,
  1750,
  2000,
  2500,
  3000,
  3500,
  4000,
  4500,
  5000,
  5500
)
longitude_sections_basin <- c(335.5, 190.5, 70.5)
longitude_sections_regular <- seq(30.5, 380.5, 20)

params_global <-
  lst(
    lat_max = 65,
    lat_min = -85,
    lat_min_SO = -35,
    lat_equator = 0,
    lon_Atl_section = 335.5,
    lon_Pac_section = 190.5,
    lon_Ind_section = 70.5,
    lat_Atl_profile = 40.5,
    lat_section_N = 59.5,
    lat_section_S = -59.5,
    longitude_sections_basin = longitude_sections_basin,
    longitude_sections_regular = longitude_sections_regular,
    inventory_depth_standard = 3000,
    inventory_depths = c(100, 500, 1000, 3000, 10000),
    plotting_depth = 4500,
    cruises_meridional = 1041,
    depth_levels = depth_levels,
    depth_levels_33 = depth_levels_33,
    breaks_cant_pos_inv = c(seq(0,16,2),Inf),
    breaks_cant_inv = c(-Inf,seq(-16,16,2),Inf),
    breaks_cant_inv_offset = c(-Inf, seq(-15, 15, 3), Inf),
    breaks_cant_pos = c(seq(0, 18, 1), Inf),
    breaks_cant = c(-Inf,seq(-16,16,2),Inf),
    breaks_cant_offset = c(-Inf,seq(-8,8,),Inf)
  )

```

# Write file

```{r write_params_global}

params_global %>%
  write_rds(
    paste(path_utilities,
          "files/params_global.rds",
          sep = "")
    )

```
