---
title: "Atmospheric pCO2"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths, include=FALSE}
path_atm_pCO2    <- "/net/kryo/work/loher/CESM_output/RECCAP2/cmorized_Dec2020/split/"
path_preprocessing  <- paste(path_root, "/model/preprocessing/", sep = "")
```

```{r load_libraries_specific, include=FALSE}
library(stars)
library(tidync)
```

# Read data

- Data source: `Globally averaged marine surface annual mean data` from [ESRL-NOAA](https://www.esrl.noaa.gov/gmd/ccgg/trends/gl_data.html)

```{r read_atm_co2}

co2_atm <- tidync(
  paste(path_atm_pCO2,
        "Atm_CO2_CESM-ETHZ_1_gr_1980-2019.nc",
        sep = "")
)

co2_atm <- co2_atm %>% 
  hyper_tibble()

co2_atm <- co2_atm %>%
  mutate(pCO2 = as.numeric(Atm_CO2), year = round(1980 + co2_atm$time_ann /
                                                    (60 * 60 * 24 * 365))) %>%
  select(year, pCO2)
  
```

# Time series

```{r co2_atm_time_series}

co2_atm %>% 
  ggplot(aes(year, pCO2)) +
  geom_path() +
  geom_point()

```

# Write clean file

```{r write_co2_atm_clean_file}

co2_atm %>%
  write_csv(paste(path_preprocessing,
                  "co2_atm.csv",
                  sep = ""))

```
