---
title: "Surface Ocean data"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths}

path_cmorized <-
  "/nfs/kryo/work/updata/reccap2/Models/2D_CO2/"

path_cmorized_ancillary <-
  "/nfs/kryo/work/updata/reccap2/Models/Ancillary_data/"

path_preprocessing <-
  paste(path_root, "/model/preprocessing/surface_ocean/", sep = "")
```

```{r load_libraries_specific, include=FALSE}
library(stars)
library(lubridate)
library(rqdatatable)
library(gsw)
library(marelac)
library(oce)
library(reticulate)
```

# Select basin mask

```{r select_basin_mask}

# use only three basin to assign general basin mask
# ie this is not specific to the MLR fitting
basinmask <- basinmask %>%
  filter(MLR_basins == "2") %>%
  select(lat, lon, basin_AIP)

```

```{r list_models}


models <- list.files(path_cmorized)

models <-
  models[!str_detect(models, pattern = "\\.t|\\.z")]

models <-
  models[str_detect(
    models,
    pattern = c(
      "CESM|CNRM|EC-Earth3|FESOM_REcoM_LR|MOM6-Princeton|MRI-ESM2-1|NorESM-OC1.2|ORCA025-GEOMAR|ORCA1-LIM3-PISCES|planktom12"
    )
  )]

# depth named lev, contains only depth levels not actual depth in m
# time not in days since 1980
models <-
  models[!str_detect(models, pattern = "CNRM")]

# no run D
models <-
  models[!str_detect(models, pattern = "MOM6-Princeton")]

```

# CESM fgco2_glob

```{r CESM_fgco2_glob}

CESM_folder <- models[str_detect(models, pattern = "CESM")]

# read list of all files
file <-
  list.files(path = paste0(path_cmorized, CESM_folder),
             pattern = paste0("fgco2_glob"))
          
print(file)
          
file[str_detect(file, pattern = paste0("_D_"))]

# read in data
variable_data_D <-
  read_ncdf(paste0(path_cmorized,
                   CESM_folder,
                   "/",
                   file[str_detect(file, pattern = paste0("_D_"))]),
            make_units = FALSE,
            var = "fgco2_glob")
variable_data_B <-
  read_ncdf(paste0(path_cmorized,
                   CESM_folder,
                   "/",
                   file[str_detect(file, pattern = paste0("_B_"))]),
            make_units = FALSE,
            var = "fgco2_glob")
          
variable_data <- variable_data_D - variable_data_B

# convert to tibble
variable_data_tibble <- variable_data %>%
  as_tibble()
          
# remove na values
variable_data_tibble <-
  variable_data_tibble %>%
  drop_na()

variable_data_tibble <- variable_data_tibble %>%
  rename(time = time_mon)

variable_data_tibble %>%
  ggplot(aes(time, fgco2_glob)) +
  geom_path()

variable_data_tibble %>% 
  filter(time > as.Date("1994-01-01"),
         time < as.Date("2003-12-31")) %>% 
  group_by(year(time)) %>%
  summarise(fgco2_glob = mean(fgco2_glob)) %>% 
  pull(fgco2_glob) %>% 
  max()

rm(variable_data, variable_data_B, variable_data_D, variable_data_tibble)
rm(CESM_folder, file)

```



# Extract surface data

```{r subset_cmorized_variable_forcing_data}



# set name of model to be subsetted
model_IDs <- c("A", "D")

# for loop across variables
variables <-
  c("spco2",
    "fgco2",
    "talkos",
    "dissicos",
    "po4os",
    "no3os",
    "sos",
    "tos")


# models <- models[8]

for (i_model in models) {
  # i_model <- models[1]
  print(i_model)
  
  for (i_model_ID in model_IDs) {
    # i_model_ID <- model_IDs[1]
    print(i_model_ID)
    
    variables_available <-
      list.files(
        path = paste0(path_cmorized, i_model),
        pattern = paste0("_", i_model_ID, "_")
      )
    
    variables_available <-
      str_split(variables_available,
                pattern = "_",
                simplify = TRUE)[, 1]
    variables_available <-
      variables_available[variables_available %in% variables]
    variables_available <- unique(variables_available)
    
    print(variables_available)
    
    
    for (i_variable in variables_available) {
      # i_variable <- variables_available[4]
      print(i_variable)
      
      # print("sleep")
      Sys.sleep(1)
      
      # read list of all files
      file <-
        list.files(
          path = paste0(path_cmorized, i_model),
          pattern = paste0(i_variable, "_")
        )
      
      print(file)
      
      file <-
        file[str_detect(file, pattern = paste0("_", i_model_ID, "_"))]
      
      file <- file[!str_detect(file, pattern = "_reg")]
      file <- file[!str_detect(file, pattern = "_glob")]
      file <- file[!str_detect(file, pattern = "dissicnatos")]
      
      print(file)
      
      # read in data
      if (i_model %in% c("EC-Earth3_2D_CO2_v20220323")) {
        variable_data <-
          read_ncdf(paste(paste0(path_cmorized, i_model),
                          file,
                          sep = "/"),
                    make_units = FALSE,
                    make_time = FALSE) %>%
          as_tibble()
        
        variable_data <- variable_data  %>%
          mutate(time = as.Date(time, origin = "1850-02-15"))
        
      } else {
        variable_data <-
          read_ncdf(paste(paste0(path_cmorized, i_model),
                          file,
                          sep = "/"),
                    make_units = FALSE)
        
      }
      
      
      # convert to tibble
      variable_data_tibble <- variable_data %>%
        as_tibble()
      
      # remove open link to nc file
      rm(variable_data)
      
      
      if (i_model == "CESM-ETHZ_2D_CO2_v20211122") {
        variable_data_tibble <- variable_data_tibble %>%
          rename(time = time_mon)
      }
      
      if (i_model == "FESOM_REcoM_LR_2D_CO2_v20211119") {
        variable_data_tibble <- variable_data_tibble %>%
          rename(lat = Lat,
                 lon = Lon,
                 time = Time) %>%
          mutate(time = as.Date(time, origin = '1980-01-01'))
      }
      
      if (i_model == "planktom12_2d_co2_v20220404") {
        variable_data_tibble <- variable_data_tibble %>%
          rename(
            lon = LONGITUDE,
            lat = LATITUDE,
            time = TIME
          )
      }
      
      
      if (i_model == "planktom12_2d_co2_v20220404" &
          i_variable == "po4os") {
        variable_data_tibble <-
          variable_data_tibble %>%
          mutate(po4os = po4os / 100)
      }
      
      # remove na values
      variable_data_tibble <-
        variable_data_tibble %>%
        drop_na()
      
      # harmonize longitudes
      variable_data_tibble <- variable_data_tibble %>%
        mutate(lon = if_else(lon < 20, lon + 360, lon))
      
      # only consider model grids within basinmask
      variable_data_tibble <-
        inner_join(variable_data_tibble, basinmask) %>%
        select(-basin_AIP)
      
      # mutate variables
      variable_data_tibble <- variable_data_tibble %>%
        mutate(year = year(time)) %>%
        select(-time)
      
      
      # calculate annual average variable
      variable_data_tibble_annual_average <-
        variable_data_tibble %>%
        fgroup_by(lat, lon, year) %>% {
          add_vars(fgroup_vars(., "unique"),
                   fmean(., keep.group_vars = FALSE))
        }
      
      # calculate climatology
      variable_data_tibble_climatology <-
        variable_data_tibble_annual_average %>%
        fselect(-year) %>%
        fgroup_by(lat, lon) %>% {
          add_vars(fgroup_vars(., "unique"),
                   fmean(., keep.group_vars = FALSE))
        }
      
      
      # surface map of variable
      print(
        map +
          geom_raster(data = variable_data_tibble_climatology,
                      aes(lon, lat, fill = !!sym(i_variable))) +
          scale_fill_viridis_c(name = i_variable) +
          labs(title = str_remove(i_model, "2D_CO2_"))
      )
      
      
      if (exists("annual")) {
        annual <- left_join(annual, variable_data_tibble_annual_average)
      }
      
      if (!exists("annual")) {
        annual <- variable_data_tibble_annual_average
      }
      
      
      # if (i_model == "MRI-ESM2-1_2D_CO2_v20220502" &
      #     !(i_variable %in% c("dissicos", "fgco2", "spco2"))) {
      #
      # }
      
    }
    
    
    if (i_model == "FESOM_REcoM_LR_2D_CO2_v20211119") {
      annual <- annual %>%
        mutate(po4os = no3os / 16)
    }
    
    if (i_model == "planktom12_3d_all_v20220404") {
      annual <- annual %>%
        mutate(no3os = po4os * 16)
    }
    
    if (i_model == "MRI-ESM2-1_2D_CO2_v20220502" &
        i_model_ID == "D") {
      annual <- right_join(annual,
                           AD_annual %>%
                             select(-c(dissicos, fgco2, spco2, model_ID)))
    }
    
    annual <- annual %>%
      mutate(model_ID = i_model_ID)
    
    if (exists("AD_annual")) {
      AD_annual <- bind_rows(AD_annual, annual)
    }
    
    if (!exists("AD_annual")) {
      AD_annual <- annual
    }
    
    rm(annual)
    
    
  }
  
  
  # harmonize column names and coordinates
  AD_annual <- AD_annual %>%
    rename(
      sal = sos,
      temp = tos,
      dissic = dissicos,
      talk = talkos,
      phosphate = po4os,
      nitrate = no3os
    ) %>%
    mutate(lon = if_else(lon < 20, lon + 360, lon))
  
  # unit transfer from mol/m3 to µmol/kg
  AD_annual <- AD_annual %>%
    mutate(
      rho = gsw_pot_rho_t_exact(
        SA = sal,
        t = temp,
        p = 0,
        p_ref = 10.1325
      ),
      dissic = dissic * (1e+6 / rho),
      talk = talk * (1e+6 / rho),
      phosphate = phosphate * (1e+6 / rho),
      nitrate = nitrate * (1e+6 / rho)
    ) %>% 
    select(-rho)
  
  
  # write raw data file for GLODAP-based subsetting model variables
  AD_annual %>%
    write_csv(file = paste(
      path_preprocessing,
      str_remove(i_model, "2D_CO2_|2D_co2_|2d_co2_"),
      ".csv",
      sep = ""
    ))
  
  rm(AD_annual)
  
}


```


# Air-sea disequilibrium

```{r air_sea_disequilibria}


# set name of model to be subsetted
# model_IDs <- c("A")
model_IDs <- c("A", "B", "C", "D")

# for loop across variables
variables <-
  c("spco2",
    "Kw",
    "pco2atm",
    "alpha",
    "fice")


mol_to_g <- 12
P <- 1e-15
m3_to_kg <- 1030
sec_to_yr <- 60 * 60 * 24 * 365

unit_conversion_to_PgCyr <-
  mol_to_g * P * sec_to_yr / m3_to_kg

# models <- models[7:length(models)]

for (i_model in models) {
  # i_model <- models[5]
  print(i_model)
  
  file <-
    list.files(path = paste0(
      path_cmorized_ancillary,
      str_replace(i_model, "2D_CO2|2D_co2|2d_co2", "Ancillary_data")
    ),
    pattern = "area")
  
  print(file)
  
  if (i_model == "CNRM-ESM2-1_2D_CO2_v20211208") {
    file <-
      file[str_detect(file, pattern = paste0("_A_"))]
  }
  
  if (i_model %in% c("ORCA025-GEOMAR_2D_CO2_v20210804",
                     "ORCA1-LIM3-PISCES_2D_CO2_v20211215")) {
    file <-
      file[str_detect(file, pattern = paste0("area_O"))]
  }
  
  if (i_model %in% c("planktom12_2d_co2_v20220404")) {
    file <-
      list.files(path = paste0(
        path_cmorized_ancillary,
        str_replace(i_model, "2D_CO2|2D_co2|2d_co2", "ancillary_data")
      ),
      pattern = "area")
    
    area_grid <-
      variable_data <-
      read_ncdf(paste0(
        path_cmorized_ancillary,
        str_replace(i_model, "2d_co2", "ancillary_data"),
        "/",
        file
      ),
      make_units = FALSE) %>%
      as_tibble()
    
  } else {
    area_grid <-
      variable_data <-
      read_ncdf(paste0(
        path_cmorized_ancillary,
        str_replace(i_model, "2D_CO2", "Ancillary_data"),
        "/",
        file
      ),
      make_units = FALSE) %>%
      as_tibble()
  }
  

  
  for (i_model_ID in model_IDs) {
    # i_model_ID <- model_IDs[1]
    print(i_model_ID)
    
    variables_available <-
      list.files(
        path = paste0(path_cmorized, i_model),
        pattern = paste0("_", i_model_ID, "_")
      )
    
    if (length(variables_available) > 0) {
      variables_available <-
        str_split(variables_available,
                  pattern = "_",
                  simplify = TRUE)[, 1]
      variables_available <-
        variables_available[variables_available %in% variables]
      variables_available <- unique(variables_available)
      
      print(variables_available)
      
      if (length(variables_available) == 5) {
        for (i_variable in variables_available) {
          # i_variable <- variables_available[1]
          
          print(i_variable)
          
          # print("sleep")
          Sys.sleep(1)
          
          # read list of all files
          file <-
            list.files(
              path = paste0(path_cmorized, i_model),
              pattern = paste0(i_variable, "_")
            )
          
          print(file)
          
          file <-
            file[str_detect(file, pattern = paste0("_", i_model_ID, "_"))]
          
          file <- file[!str_detect(file, pattern = "_reg")]
          file <- file[!str_detect(file, pattern = "_glob")]
          file <- file[!str_detect(file, pattern = "dissicnatos")]
          
          print(file)
          
          # read in data
          variable_data <-
            read_ncdf(paste0(path_cmorized,
                             i_model,
                             "/",
                             file),
                      make_units = FALSE)
          
          # convert to tibble
          variable_data_tibble <- variable_data %>%
            as_tibble()
          
          # remove open link to nc file
          rm(variable_data)
          
          # remove na values
          variable_data_tibble <-
            variable_data_tibble %>%
            drop_na()
          
          
          if (exists("all_variables")) {
            all_variables <- inner_join(all_variables, variable_data_tibble)
          }
          
          if (!exists("all_variables")) {
            all_variables <- variable_data_tibble
          }
          
          
        }
        
        all_variables <- inner_join(all_variables,
                                    area_grid)
        
        if (i_model == "CESM-ETHZ_2D_CO2_v20211122") {
          all_variables <- all_variables %>%
            rename(time = time_mon)
        }
        
        if (i_model == "FESOM_REcoM_LR_2D_CO2_v20211119") {
          all_variables <- all_variables %>%
            rename(lat = Lat,
                   lon = Lon,
                   time = Time) %>%
            mutate(time = as.Date(time, origin = '1980-01-01'))
        }
        
        # harmonize longitudes
        all_variables <- all_variables %>%
          mutate(lon = if_else(lon < 20, lon + 360, lon))
        
        # only consider model grids within basinmask
        all_variables <-
          inner_join(all_variables, basinmask) %>%
          select(-basin_AIP)
        
        
        all_variables <- all_variables %>%
          mutate(
            delta_pco2 = spco2 - pco2atm,
            scale = area * Kw * alpha * (1 - fice),
            fgco2 = delta_pco2 * scale
          )
        
        delta_pco2_monthly <- all_variables %>%
          group_by(time) %>%
          summarise(
            scaling_glob = sum(scale),
            fgco2_glob = sum(fgco2),
            delta_pco2_glob = fgco2_glob / scaling_glob
          ) %>%
          ungroup() %>%
          mutate(fgco2_glob = fgco2_glob * unit_conversion_to_PgCyr)
        
        delta_pco2_annual <- delta_pco2_monthly %>%
          mutate(year = year(time)) %>%
          group_by(year) %>%
          summarise(
            scaling_glob = mean(scaling_glob),
            fgco2_glob = mean(fgco2_glob),
            delta_pco2_glob = mean(delta_pco2_glob)
          ) %>%
          ungroup()
        
        print(
          ggplot() +
            geom_path(
              data = delta_pco2_monthly,
              aes(decimal_date(time), delta_pco2_glob, col = "monthly")
            ) +
            geom_path(data = delta_pco2_annual,
                      aes(year, delta_pco2_glob, col = "annual")) +
            scale_color_brewer(palette = "Set1", name = "Average") +
            labs(
              title = paste(
                str_remove(i_model, "2D_CO2_"),
                "| model_id:",
                i_model_ID
              ),
              x = "year"
            )
        )
        
        print(
          ggplot() +
            geom_path(data = delta_pco2_monthly,
                      aes(
                        decimal_date(time), fgco2_glob, col = "monthly"
                      )) +
            geom_path(data = delta_pco2_annual,
                      aes(year, fgco2_glob, col = "annual")) +
            scale_color_brewer(palette = "Set1", name = "Average") +
            labs(
              title = paste(
                str_remove(i_model, "2D_CO2_") ,
                "| model_id:",
                i_model_ID
              ),
              x = "year"
            )
        )
        
        print(ggplot() +
                geom_path(
                  data = delta_pco2_annual,
                  aes(year,
                      scaling_glob * unit_conversion_to_PgCyr)
                ))
        
        print(
          ggplot() +
            geom_path(
              data = delta_pco2_annual,
              aes(
                year,
                scaling_glob * delta_pco2_glob * unit_conversion_to_PgCyr,
                col = "scaled"
              )
            ) +
            geom_path(data = delta_pco2_annual,
                      aes(year, fgco2_glob, col = "integrated")) +
            scale_color_brewer(palette = "Set1", name = "Estimate") +
            scale_y_continuous(name = "Air-sea flux [PgC yr-1]") +
            labs(
              title = paste(
                str_remove(i_model, "2D_CO2_"),
                "| model_id:",
                i_model_ID
              ),
              x = "year"
            )
        )
        
        # write raw data file for GLODAP-based subsetting model variables
        delta_pco2_annual %>%
          select(-c(scaling_glob, fgco2_glob)) %>%
          write_csv(
            file = paste0(
              path_preprocessing,
              "surface_ocean_disequilibrium/",
              str_remove(i_model, "2D_CO2_"),
              "_",
              i_model_ID,
              "_annual.csv"
            )
          )
        
        rm(i_variable,
           all_variables,
           delta_pco2_annual,
           delta_pco2_monthly)
        
      }
    }
  }
}


  
  
```
